<a href="https://colab.research.google.com/github/zainamri/tugas/blob/main/TugasPert2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Zainab (15230008)



In [19]:
pip install numpy

In [6]:
import numpy

In [7]:
numpy.__version__

'1.25.2'

In [12]:
import numpy as np

In [13]:
grid=np.arange(11,36).reshape((5,5))
print(grid)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [16]:
def warna_angka(angka):
    if angka in [11, 13, 15, 21, 23, 25, 31, 33, 35]:
        return "\033[32m{}\033[0m".format(angka) # Hijau
    elif angka in [12, 14]:
        return "\033[31m{}\033[0m".format(angka) # Merah
    elif angka in [16, 26]:
        return "\033[34m{}\033[0m".format(angka) # Biru
    elif angka in [12, 17, 22, 27, 32]:
        return "\033[91m{}\033[0m".format(angka) # Merah Muda
    else:
        return str(angka)

In [18]:
# Mengubah setiap elemen matriks dengan fungsi warna_angka
grid_warna = np.vectorize(warna_angka)(grid)
#menampilkan warna pada bagian yang di pilih
for baris in grid_warna:
    print(" ".join(baris))

11 12 13 14 15
16 17 18 19 20
21 22 23 24 25
26 27 28 29 30
31 32 33 34 35
